# Base configs
baseurl: "https://www.SpiralRhapsody.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Spiral Rhapsody"
# subtitle: ""
author: "Curated by Dyvers Hands"
header:
 title: "Spiral Rhapsody"
 author: "Curated by Dyvers Hands"
footer:
 name: "Dyvers Hands"
 #bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "DH"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/DyversHands"
  #instagram: "https://www.instagram.com/ram_patra"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/DyversHands"
