# Base configs
baseurl: "https://www.SpiralRhapsody.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Spiral Rhapsody"
# subtitle: ""
author: "Dyvers Hands Productions, LLC"
header:
 title: "A Spiral Rhapsody"
 author: "Curated by Christopher Allen"
footer:
 name: "A Spiral Rhapsody"
 bio: |
   "the intervals change.
   the notes braid into a fugue.
   a major charges forward.
   a minor follows,
   descending toward a conclusion
   the up-and-down turns left
   and i forget to breathe.
   i’m dizzy with a kind of living.
   i am a thread of things spun loose and coiling back on themselves.
   in a spiral rhapsody. " -- Christopher Allen
#github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "Christopher Allen"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/DyversHands"
  #instagram: "https://www.instagram.com/ram_patra"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/DyversHands"
